create table users
(
    id       bigint generated by default as identity primary key,
    username varchar unique not null,
    password varchar        not null,
    email    varchar unique not null,
    role     varchar        not null
);