create table users
(
    id        bigint generated by default as identity primary key,
    username  varchar unique not null,
    password  varchar        not null,
    email     varchar unique not null,
    role      varchar        not null,
    is_enable boolean
);
create table activation
(
    id      bigint generated by default as identity primary key,
    key     varchar                                               not null unique,
    user_id bigint references users (id) on delete cascade unique not null
);

